/* Generated by cbindgen - DO NOT EDIT.
 *
 * jgpmf C API: parses GoPro GPMF sample payloads.
 *
 * Returned pointers from jgpmf_sample_accl / _gyro / _grav / _cori / _iori
 * alias into memory owned by the JgpmfSample and become invalid after the
 * corresponding jgpmf_sample_free call.
 */

#ifndef JGPMF_CAPI_H
#define JGPMF_CAPI_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Return status for every `jgpmf_*` entry point. Zero is success.
 */
typedef enum {
  JGPMF_OK = 0,
  /**
   * One of the required pointer arguments was null.
   */
  JGPMF_ERR_NULL_ARG = 1,
  /**
   * The byte payload could not be parsed as GPMF.
   */
  JGPMF_ERR_PARSE = 2,
  /**
   * The payload parsed but contained no `DEVC` root container.
   */
  JGPMF_ERR_NO_DEVC = 3,
  /**
   * The sample has no usable `GPS9` data (no fix, missing stream, etc.).
   */
  JGPMF_ERR_NO_GPS9 = 4,
  /**
   * An index argument was out of range.
   */
  JGPMF_ERR_OUT_OF_RANGE = 5,
} JgpmfStatus;

/**
 * Opaque parsed-sample handle. Allocated by `jgpmf_sample_parse`, freed by
 * `jgpmf_sample_free`.
 */
typedef struct {
  uint8_t _opaque[0];
} JgpmfSample;

/**
 * Mirror of `gpmf_parser::Gps9`, exposed to C as a plain value type.
 */
typedef struct {
  uint32_t fix;
  float dop;
  float latitude;
  float longitude;
  /**
   * Altitude in metres.
   */
  float altitude;
  /**
   * 2D speed in m/s.
   */
  float speed_2d;
  /**
   * 3D speed in m/s.
   */
  float speed_3d;
  float days_since_2000;
  float seconds_since_midnight;
} JgpmfGps9;

/**
 * 3-component vector in raw KLV axis order.
 */
typedef struct {
  float x;
  float y;
  float z;
} JgpmfVec3;

/**
 * Quaternion in raw KLV component order: (w, x, y, z).
 */
typedef struct {
  float w;
  float x;
  float y;
  float z;
} JgpmfQuat;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Parses one GPMF sample payload.
 *
 * On success, writes an owned handle to `*out_sample` (must be released with
 * `jgpmf_sample_free`) and returns `JGPMF_OK`.
 *
 * # Safety
 * `bytes` must point to at least `len` valid bytes for the duration of the
 * call. `out_sample` must point to a writable `JgpmfSample*` slot.
 */
JgpmfStatus jgpmf_sample_parse(const uint8_t *bytes, size_t len, JgpmfSample **out_sample);

/**
 * Releases a handle returned by `jgpmf_sample_parse`. Passing null is a no-op.
 *
 * # Safety
 * `sample` must be a pointer previously returned by `jgpmf_sample_parse` and
 * not yet freed. After this call the pointer is invalid.
 */
void jgpmf_sample_free(JgpmfSample *sample);

/**
 * Copies the parsed `GPS9` value into `*out`. Returns `JGPMF_OK` on success,
 * `JGPMF_ERR_NO_GPS9` if the sample has `fix == 0` (no GPS fix).
 *
 * # Safety
 * `out` must point to a writable `JgpmfGps9` slot.
 */
JgpmfStatus jgpmf_sample_get_gps9(const JgpmfSample *sample, JgpmfGps9 *out);

/**
 * Borrows the sample's accelerometer array (m/s² after SCAL). The pointer
 * remains valid until `jgpmf_sample_free` is called on the same handle.
 * An empty stream produces `*out_count == 0` and `*out_ptr` unspecified.
 *
 * # Safety
 * `out_ptr` / `out_count` must be writable.
 */
JgpmfStatus jgpmf_sample_accl(const JgpmfSample *sample,
                              const JgpmfVec3 **out_ptr,
                              size_t *out_count);

/**
 * Borrows the sample's gyroscope array (rad/s after SCAL).
 *
 * # Safety
 * See [`jgpmf_sample_accl`].
 */
JgpmfStatus jgpmf_sample_gyro(const JgpmfSample *sample,
                              const JgpmfVec3 **out_ptr,
                              size_t *out_count);

/**
 * Borrows the sample's gravity-vector array.
 *
 * # Safety
 * See [`jgpmf_sample_accl`].
 */
JgpmfStatus jgpmf_sample_grav(const JgpmfSample *sample,
                              const JgpmfVec3 **out_ptr,
                              size_t *out_count);

/**
 * Borrows the sample's camera-orientation quaternion array.
 *
 * # Safety
 * See [`jgpmf_sample_accl`].
 */
JgpmfStatus jgpmf_sample_cori(const JgpmfSample *sample,
                              const JgpmfQuat **out_ptr,
                              size_t *out_count);

/**
 * Borrows the sample's image-orientation quaternion array.
 *
 * # Safety
 * See [`jgpmf_sample_accl`].
 */
JgpmfStatus jgpmf_sample_iori(const JgpmfSample *sample,
                              const JgpmfQuat **out_ptr,
                              size_t *out_count);

/**
 * Library semantic version. Any out-parameter may be null.
 *
 * # Safety
 * Each non-null pointer must be writable.
 */
void jgpmf_version(uint32_t *major, uint32_t *minor, uint32_t *patch);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* JGPMF_CAPI_H */
